# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CityTimer
                                 A QGIS plugin
 temp description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-07-22
        copyright            : (C) 2022 by Carlo Andrea Biraghi, Andrea Folini
        email                : carloandrea.biraghi@polimi.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Carlo Andrea Biraghi, Andrea Folini'
__date__ = '2022-07-22'
__copyright__ = '(C) 2022 by Carlo Andrea Biraghi, Andrea Folini'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CityTimer class from file CityTimer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .city_timer import CityTimerPlugin
    return CityTimerPlugin()
